---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckad-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /tmp/ckad
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckad-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: fast
  volumeName: ckad-pv
